// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARjTsKMlgtafP_9CHAWTxgtqoYft9sDHo',
    appId: '1:264083831090:web:b3cbddd60c3d7a74fcbf2b',
    messagingSenderId: '264083831090',
    projectId: 'akilli-tarim-sistemi',
    authDomain: 'akilli-tarim-sistemi.firebaseapp.com',
    storageBucket: 'akilli-tarim-sistemi.firebasestorage.app',
    measurementId: 'G-NXX2NH833T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASChGXrBksuxOz1_nUwQ6Y12ujBj5vZgA',
    appId: '1:264083831090:android:4f73fdfb08c87a58fcbf2b',
    messagingSenderId: '264083831090',
    projectId: 'akilli-tarim-sistemi',
    storageBucket: 'akilli-tarim-sistemi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcXBTlZ54Sek0KX8Oo4XzGPNNpGQYKBdQ',
    appId: '1:264083831090:ios:288e43c64bb79f16fcbf2b',
    messagingSenderId: '264083831090',
    projectId: 'akilli-tarim-sistemi',
    storageBucket: 'akilli-tarim-sistemi.firebasestorage.app',
    iosClientId: '264083831090-3vto5mqti8uqf9m49qc6mscff7u0u0rc.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterBitirme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcXBTlZ54Sek0KX8Oo4XzGPNNpGQYKBdQ',
    appId: '1:264083831090:ios:288e43c64bb79f16fcbf2b',
    messagingSenderId: '264083831090',
    projectId: 'akilli-tarim-sistemi',
    storageBucket: 'akilli-tarim-sistemi.firebasestorage.app',
    iosClientId: '264083831090-3vto5mqti8uqf9m49qc6mscff7u0u0rc.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterBitirme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARjTsKMlgtafP_9CHAWTxgtqoYft9sDHo',
    appId: '1:264083831090:web:9038de9e758af681fcbf2b',
    messagingSenderId: '264083831090',
    projectId: 'akilli-tarim-sistemi',
    authDomain: 'akilli-tarim-sistemi.firebaseapp.com',
    storageBucket: 'akilli-tarim-sistemi.firebasestorage.app',
    measurementId: 'G-HG6QSDNQ69',
  );
}
